-- Drop all existing tables and enums
DO $$
DECLARE
    r RECORD;
BEGIN
    -- Drop all tables
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;

    -- Drop all enums
    FOR r IN (SELECT t.typname FROM pg_type t LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE t.typtype = 'e' AND n.nspname = 'public') LOOP
        EXECUTE 'DROP TYPE IF EXISTS ' || quote_ident(r.typname) || ' CASCADE';
    END LOOP;
END $$;

-- Create Enums
CREATE TYPE "Visibility" AS ENUM ('ORG', 'TEAM', 'SELF');
CREATE TYPE "DaysOfWeek" AS ENUM ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY');
CREATE TYPE "AccuralFrequencyOptions" AS ENUM ('BIWEEKLY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY');
CREATE TYPE "AccrueOnOptions" AS ENUM ('BEGINNING', 'END');
CREATE TYPE "LeaveDuration" AS ENUM ('FULL_DAY', 'HALF_DAY');
CREATE TYPE "Shift" AS ENUM ('MORNING', 'AFTERNOON', 'NONE');
CREATE TYPE "LeaveStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'DELETED');
CREATE TYPE "Role" AS ENUM ('OWNER', 'MANAGER', 'USER', 'ANON');

-- Create Tables
CREATE TABLE "Organisation" (
    "orgId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" VARCHAR(255) NOT NULL,
    "dateformat" VARCHAR(255) NOT NULL DEFAULT 'DD-MM-YYYY',
    "timeformat" VARCHAR(255) NOT NULL DEFAULT 'HH:MM',
    "location" VARCHAR(255),
    "visibility" "Visibility" NOT NULL DEFAULT 'SELF',
    "startOfWorkWeek" "DaysOfWeek" NOT NULL DEFAULT 'MONDAY',
    "workweek" "DaysOfWeek"[] NOT NULL DEFAULT ARRAY['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']::"DaysOfWeek"[],
    "timeZone" VARCHAR(255),
    "notificationLeaveChanged" BOOLEAN NOT NULL DEFAULT FALSE,
    "notificationDailySummary" BOOLEAN NOT NULL DEFAULT FALSE,
    "notificationDailySummarySendOnTime" TEXT,
    "notificationWeeklySummary" BOOLEAN NOT NULL DEFAULT FALSE,
    "notificationWeeklySummaryTime" TEXT,
    "notificationWeeklySummarySendOnDay" "DaysOfWeek",
    "notificationToWhom" "Role" NOT NULL DEFAULT 'MANAGER',
    "ownerId" UUID,
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    "halfDayLeave" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE "Team" (
    "teamId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" VARCHAR(255) NOT NULL,
    "orgId" UUID NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "manager" UUID,
    "location" VARCHAR(255),
    "startOfWorkWeek" "DaysOfWeek"  DEFAULT 'MONDAY',
    "workweek" "DaysOfWeek"[]  DEFAULT ARRAY['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']::"DaysOfWeek"[],
    "timeZone" VARCHAR(255),
    "notificationLeaveChanged" BOOLEAN NOT NULL DEFAULT FALSE,
    "notificationDailySummary" BOOLEAN NOT NULL DEFAULT FALSE,
    "notificationDailySummarySendOnTime" TEXT,
    "notificationWeeklySummary" BOOLEAN NOT NULL DEFAULT FALSE,
    "notificationWeeklySummaryTime" TEXT,
    "notificationWeeklySummarySendOnDay" "DaysOfWeek",
    "notificationToWhom" "Role" NOT NULL DEFAULT 'MANAGER',
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    CONSTRAINT "fk_team_org" FOREIGN KEY ("orgId") REFERENCES "Organisation"("orgId")
);

CREATE TABLE "User" (
    "userId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "teamId" UUID,
    "role" "Role" NOT NULL DEFAULT 'USER',
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    "accruedLeave" JSON DEFAULT '{}'::json,
    "usedLeave" JSON DEFAULT '{}'::json,
    "keyword" VARCHAR,
    "slackId" TEXT,
    "googleId" TEXT,
    "orgId" UUID,
    CONSTRAINT "fk_user_team" FOREIGN KEY ("teamId") REFERENCES "Team"("teamId") ON DELETE RESTRICT,
    CONSTRAINT "fk_user_org" FOREIGN KEY ("orgId") REFERENCES "Organisation"("orgId")
);

CREATE TABLE "Leave" (
    "leaveId" UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    "leaveType" VARCHAR(255) NOT NULL,
    "startDate" DATE NOT NULL,
    "endDate" DATE NOT NULL,
    "duration" "LeaveDuration" NOT NULL,
    "shift" "Shift" NOT NULL,
    "isApproved" "LeaveStatus" NOT NULL DEFAULT 'PENDING',
    "userId" UUID NOT NULL,
    "teamId" UUID NOT NULL,
    "reason" VARCHAR(255),
    "managerComment" VARCHAR(255),
    "orgId" UUID NOT NULL,
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    CONSTRAINT "fk_leave_user" FOREIGN KEY  ("userId") REFERENCES "User" ("userId"),
    CONSTRAINT "fk_leave_team" FOREIGN KEY  ("teamId") REFERENCES "Team" ("teamId"),
    CONSTRAINT "fk_leave_org" FOREIGN KEY  ("orgId") REFERENCES "Organisation" ("orgId")
);

CREATE TABLE "LeaveType" (
    "leaveTypeId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" VARCHAR(255) NOT NULL,
    "color" VARCHAR(6),
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "orgId" UUID NOT NULL,
    "setSlackStatus" BOOLEAN NOT NULL DEFAULT TRUE,
    "emoji" VARCHAR,
    "statusMsg" VARCHAR(255),
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    CONSTRAINT "fk_leavetype_org" FOREIGN KEY ("orgId") REFERENCES "Organisation"("orgId")
);

CREATE TABLE "LeavePolicy" (
    "leavePolicyId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "leaveTypeId" UUID NOT NULL,
    "unlimited" BOOLEAN NOT NULL DEFAULT FALSE,
    "maxLeaves" INT,
    "accruals" BOOLEAN NOT NULL DEFAULT FALSE,
    "accrualFrequency" "AccuralFrequencyOptions",
    "accrueOn" "AccrueOnOptions",
    "rollOver" BOOLEAN NOT NULL DEFAULT FALSE,
    "rollOverLimit" INT,
    "orgId" UUID NOT NULL,
    "rollOverExpiry" VARCHAR(5) CHECK ("rollOverExpiry" ~ '^\d{2}/\d{2}$'),
    "autoApprove" BOOLEAN NOT NULL DEFAULT FALSE,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    CONSTRAINT "fk_leavepolicy_org" FOREIGN KEY ("orgId") REFERENCES "Organisation"("orgId"),
    CONSTRAINT "fk_leavepolicy_leavetype" FOREIGN KEY ("leaveTypeId") REFERENCES "LeaveType"("leaveTypeId")
);


CREATE TABLE "Holiday" (
    "holidayId" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" VARCHAR(255) NOT NULL,
    "date" TIMESTAMP(6) NOT NULL,
    "location" VARCHAR(255),
    "isRecurring" BOOLEAN NOT NULL DEFAULT TRUE,
    "isCustom" BOOLEAN NOT NULL DEFAULT TRUE,
    "orgId" UUID NOT NULL,
    "createdOn" TIMESTAMP(6) DEFAULT now(),
    "createdBy" VARCHAR(255),
    "updatedBy" VARCHAR(255),
    "updatedOn" TIMESTAMP(6) DEFAULT now(),
    CONSTRAINT "fk_holiday_org" FOREIGN KEY ("orgId") REFERENCES "Organisation"("orgId")
);

CREATE TABLE "OrgActivityLog" (
    "id" SERIAL PRIMARY KEY,
    "orgId" UUID,
    "changedColumns" TEXT[],
    "oldValues" JSON,
    "newValues" JSON,
    "changedOn" TIMESTAMP(6) DEFAULT now(),
    "changedBy" VARCHAR(255),
    "tableName" VARCHAR,
    "teamId" UUID,
    "userId" UUID,
    "keyword" VARCHAR
);

CREATE TABLE "PublicHolidays" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    country varchar(50),
    iso char(2),
    year int,
    date DATE,
    day varchar(15),
    name varchar(100),
    type varchar(50)
  );

INSERT INTO "PublicHolidays" (country, iso, year, date, day, name, type) VALUES
('India', 'IN', 2025, '2025-01-01', 'Wednesday', 'New Year''s Day', 'RESTRICTED_HOLIDAY'),
('India', 'IN', 2025, '2025-01-13', 'Monday', 'Lohri', 'RESTRICTED_HOLIDAY'),
('India', 'IN', 2025, '2025-01-26', 'Sunday', 'Republic Day', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-03-14', 'Friday', 'Dolyatra', 'RESTRICTED_HOLIDAY'),
('India', 'IN', 2025, '2025-04-06', 'Sunday', 'Rama Navami', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-04-10', 'Thursday', 'Mahavir Jayanti', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-04-14', 'Monday', 'Ambedkar Jayanti', 'OBSERVANCE'),
('India', 'IN', 2025, '2025-04-18', 'Friday', 'Good Friday', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-05-12', 'Monday', 'Buddha Purnima/Vesak', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-06-07', 'Saturday', 'Bakr Id/Eid ul-Adha (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-07-06', 'Sunday', 'Muharram/Ashura (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-08-16', 'Saturday', 'Janmashtami', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-10-02', 'Thursday', 'Dussehra', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-10-20', 'Monday', 'Diwali/Deepavali', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-11-05', 'Wednesday', 'Guru Nanak Jayanti', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2025, '2025-12-25', 'Thursday', 'Christmas', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-01-26', 'Monday', 'Republic Day', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-03-04', 'Wednesday', 'Holi', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-03-26', 'Thursday', 'Rama Navami', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-04-03', 'Friday', 'Good Friday', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-04-14', 'Tuesday', 'Ambedkar Jayanti', 'OBSERVANCE'),
('India', 'IN', 2026, '2026-05-27', 'Wednesday', 'Bakr Id/Eid ul-Adha (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-06-26', 'Friday', 'Muharram/Ashura (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-08-15', 'Saturday', 'Independence Day', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-10-02', 'Friday', 'Mahatma Gandhi Jayanti', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-10-20', 'Tuesday', 'Dussehra', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-11-08', 'Sunday', 'Diwali/Deepavali', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2026, '2026-12-25', 'Friday', 'Christmas', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-01-14', 'Sunday', 'Lohri', 'RESTRICTED_HOLIDAY'),
('India', 'IN', 2024, '2024-01-26', 'Friday', 'Republic Day', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-03-25', 'Monday', 'Dolyatra', 'RESTRICTED_HOLIDAY'),
('India', 'IN', 2024, '2024-03-29', 'Friday', 'Good Friday', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-04-10', 'Wednesday', 'Ramzan Id/Eid-ul-Fitar (Tentative Date)', 'MUSLIM_COMMON_LOCAL_HOLIDAY'),
('India', 'IN', 2024, '2024-04-14', 'Sunday', 'Ambedkar Jayanti', 'OBSERVANCE'),
('India', 'IN', 2024, '2024-04-17', 'Wednesday', 'Rama Navami', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-04-21', 'Sunday', 'Mahavir Jayanti', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-05-23', 'Thursday', 'Buddha Purnima/Vesak', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-06-17', 'Monday', 'Bakr Id/Eid ul-Adha (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-07-17', 'Wednesday', 'Muharram/Ashura (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-09-16', 'Monday', 'Milad un-Nabi/Id-e-Milad (Tentative Date)', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-10-02', 'Wednesday', 'Mahatma Gandhi Jayanti', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-10-12', 'Saturday', 'Dussehra', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-11-01', 'Friday', 'Diwali/Deepavali', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-11-15', 'Friday', 'Guru Nanak Jayanti', 'GAZETTED_HOLIDAY'),
('India', 'IN', 2024, '2024-12-25', 'Wednesday', 'Christmas', 'GAZETTED_HOLIDAY'),
('Germany', 'DE', 2024, '2024-05-01', 'Wednesday', 'May Day', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2024, '2024-05-20', 'Monday', 'Whit Monday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2024, '2024-12-26', 'Thursday', 'Boxing Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2024, '2024-10-03', 'Thursday', 'Day of German Unity', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2024, '2024-12-25', 'Wednesday', 'Christmas Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2024, '2024-01-01', 'Monday', 'New Year''s Day', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2024, '2024-03-29', 'Friday', 'Good Friday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2024, '2024-04-01', 'Monday', 'Easter Monday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2025, '2025-05-01', 'Thursday', 'May Day', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2025, '2025-12-26', 'Friday', 'Boxing Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2025, '2025-10-03', 'Friday', 'Day of German Unity', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2025, '2025-12-25', 'Thursday', 'Christmas Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2025, '2025-01-01', 'Wednesday', 'New Year''s Day', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2025, '2025-04-18', 'Friday', 'Good Friday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2025, '2025-04-21', 'Monday', 'Easter Monday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2026, '2026-05-01', 'Friday', 'May Day', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2026, '2026-12-26', 'Saturday', 'Boxing Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2026, '2026-10-03', 'Saturday', 'Day of German Unity', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2026, '2026-12-25', 'Friday', 'Christmas Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2026, '2026-01-01', 'Thursday', 'New Year''s Day', 'NATIONAL_HOLIDAY'),
('Germany', 'DE', 2026, '2026-04-03', 'Friday', 'Good Friday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2026, '2026-04-06', 'Monday', 'Easter Monday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2026, '2026-05-14', 'Thursday', 'Ascension Day', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Germany', 'DE', 2026, '2026-05-25', 'Monday', 'Whit Monday', 'NATIONAL_HOLIDAY_CHRISTIAN'),
('Netherlands', 'NL', 2024, '2024-03-29', 'Friday', 'Good Friday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-05-20', 'Monday', 'Whit Monday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-05-19', 'Sunday', 'Whit Sunday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-05-09', 'Thursday', 'Ascension Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-04-01', 'Monday', 'Easter Monday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-04-27', 'Saturday', 'King''s Birthday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-03-31', 'Sunday', 'Easter Sunday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-12-26', 'Thursday', 'Second Day of Christmas', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-12-25', 'Wednesday', 'Christmas Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-01-01', 'Monday', 'New Year''s Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2024, '2024-05-05', 'Sunday', 'Liberation Day', 'PUBLIC_SECTOR'),
('Netherlands', 'NL', 2025, '2025-06-09', 'Monday', 'Whit Monday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-04-20', 'Sunday', 'Easter Sunday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-06-08', 'Sunday', 'Whit Sunday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-04-21', 'Monday', 'Easter Monday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-12-26', 'Friday', 'Second Day of Christmas', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-04-26', 'Saturday', 'King''s Birthday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-04-18', 'Friday', 'Good Friday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-12-25', 'Thursday', 'Christmas Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-01-01', 'Wednesday', 'New Year''s Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-05-29', 'Thursday', 'Ascension Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2025, '2025-05-05', 'Monday', 'Liberation Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-05-24', 'Sunday', 'Whit Sunday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-05-14', 'Thursday', 'Ascension Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-04-06', 'Monday', 'Easter Monday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-04-27', 'Monday', 'King''s Birthday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-04-05', 'Sunday', 'Easter Sunday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-12-26', 'Saturday', 'Second Day of Christmas', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-04-03', 'Friday', 'Good Friday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-01-01', 'Thursday', 'New Year''s Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-12-25', 'Friday', 'Christmas Day', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-05-25', 'Monday', 'Whit Monday', 'NATIONAL_HOLIDAY'),
('Netherlands', 'NL', 2026, '2026-05-05', 'Tuesday', 'Liberation Day', 'PUBLIC_SECTOR'),
('United Kingdom', 'GB', 2024, '2024-05-27', 'Monday', 'Spring Bank Holiday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2024, '2024-03-29', 'Friday', 'Good Friday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2024, '2024-12-26', 'Thursday', 'Boxing Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2024, '2024-05-06', 'Monday', 'Early May Bank Holiday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2024, '2024-12-25', 'Wednesday', 'Christmas Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2024, '2024-01-01', 'Monday', 'New Year''s Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2025, '2025-05-26', 'Monday', 'Spring Bank Holiday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2025, '2025-12-26', 'Friday', 'Boxing Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2025, '2025-01-01', 'Wednesday', 'New Year''s Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2025, '2025-04-18', 'Friday', 'Good Friday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2025, '2025-12-25', 'Thursday', 'Christmas Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2025, '2025-05-05', 'Monday', 'Early May Bank Holiday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2026, '2026-12-26', 'Saturday', 'Boxing Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2026, '2026-04-03', 'Friday', 'Good Friday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2026, '2026-05-04', 'Monday', 'Early May Bank Holiday', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2026, '2026-01-01', 'Thursday', 'New Year''s Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2026, '2026-12-25', 'Friday', 'Christmas Day', 'BANK_HOLIDAY'),
('United Kingdom', 'GB', 2026, '2026-05-25', 'Monday', 'Spring Bank Holiday', 'BANK_HOLIDAY'),
('United States', 'US', 2024, '2024-01-01', 'Monday', 'New Year''s Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-01-15', 'Monday', 'Birthday of Martin Luther King, Jr.', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-02-19', 'Monday', 'Washington''s Birthday', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-05-27', 'Monday', 'Memorial Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-06-19', 'Wednesday', 'Juneteenth National Independence Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-07-04', 'Thursday', 'Independence Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-09-02', 'Monday', 'Labor Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-10-14', 'Monday', 'Columbus Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-11-11', 'Monday', 'Veterans Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-11-28', 'Thursday', 'Thanksgiving Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2024, '2024-12-25', 'Wednesday', 'Christmas Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-01-01', 'Wednesday', 'New Year''s Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-01-20', 'Monday', 'Birthday of Martin Luther King, Jr.', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-02-17', 'Monday', 'Washington''s Birthday', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-05-26', 'Monday', 'Memorial Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-06-19', 'Thursday', 'Juneteenth National Independence Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-07-04', 'Friday', 'Independence Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-09-01', 'Monday', 'Labor Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-10-13', 'Monday', 'Columbus Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-11-11', 'Tuesday', 'Veterans Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-11-27', 'Thursday', 'Thanksgiving Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2025, '2025-12-25', 'Thursday', 'Christmas Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-01-01', 'Thursday', 'New Year''s Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-01-19', 'Monday', 'Birthday of Martin Luther King, Jr.', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-02-16', 'Monday', 'Washington''s Birthday', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-05-25', 'Monday', 'Memorial Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-06-19', 'Friday', 'Juneteenth National Independence Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-07-04', 'Saturday', 'Independence Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-09-07', 'Monday', 'Labor Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-10-12', 'Monday', 'Columbus Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-11-11', 'Wednesday', 'Veterans Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-11-26', 'Thursday', 'Thanksgiving Day', 'PUBLIC_HOLIDAY'),
('United States', 'US', 2026, '2026-12-25', 'Friday', 'Christmas Day', 'PUBLIC_HOLIDAY');
